# Generated by Django 5.0.7 on 2024-09-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('warranty_period', models.PositiveIntegerField(help_text='Warranty period in months')),
            ],
        ),
    ]
