# Generated by Django 5.0.7 on 2024-09-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
